import { Geist, Geist_Mono, Caveat_Brush } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import ChatBot from "./components/chatbot/chatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat  = Caveat_Brush({
  variable: "--font-caveat-brush",
  weight: "400"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${caveat.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <ChatBot/>
      </body>
    </html>
  );
}
